export let ForYou = [
]

export let PathwayInfo = [
    {icon: 1, title: "What is the RAPID clinic?", description: "The Rapid Diagnostic and Assessment Centre (RDAC) is one of the most advanced centres of its kind in the UK. It is designed for patients with suspected cancer to ensure they receive the very best diagnostic tests and care without delay. At the RDAC we run one-stop, new-patient assessment clinics for breast, prostate and skin cancer. Most patients get their results or a form of diagnosis on the same day as their tests. All patients are seen within two weeks of referral."},
    {icon: 1, title: "What do I need to do before the appointment?", description: "You will need to come to the hospital before your appointment to have a blood test and provide a urine sample. It is important that you do get this done as it will prevent any delay in diagnosing your problem.  We will telephone you before your appointment and arrange for this to be done."},
    {icon: 1, title: "Who will I see in the clinic?", description: "You will be seen in the clinic by one of the Urology RAPID Diagnostic Team, this could be a Doctor or a Nurse. A team of administrators also support the clinic."},
    {icon: 1, title: "How long will my appointment last?", description: "Appointments can last up to five hours depending on the number of tests that you need to diagnose your problem."},
    {icon: 1, title: "What will I need to bring to the clinic?", description: "Please bring anything to clinic that will help us understand your problem better, for example: a list of current medications including those prescribed by your GP, medicines you have bought yourself or alternative medicines, such as herbal remedies. If you are being referred from another hospital please bring any relevant correspondence. Please also bring a list of your past medical history."},
    {icon: 1, title: "Do I need to bring anyone with me?", description: "You don’t have to bring anyone with you to clinic but most people find that it is useful to bring someone with them."},
    {icon: 1, title: "What can I expect from the clinic?", description: "In order for us to diagnose your problem you will need to undergo a few tests during the clinic visit. This could include a flow rate test, digital rectal exam, International Prostate Symptom Score (IPSS), magnetic resonance imaging (MRI), or a prostate biopsy."},
    {icon: 1, title: "What is an MRI?", description: "Magnetic resonance imaging (MRI) is a type of scan that uses strong magnetic fields and radio waves to produce detailed images of the inside of the body. An MRI scanner is a large tube that contains powerful magnets. You lie inside the tube during the scan. The scan does not hurt, however it can be loud. Consequently, you will be given earplugs or headphones."},
]

export let DiseaseInfo = [
    {icon: 2, title: "What is the prostate?", description: "The prostate is a small gland found only in men. It surrounds the tube that carries urine out of the body (urethra). The prostate gland produces a thick, white fluid that gets mixed with sperm to create semen. The prostate gland is about the size and shape of a walnut but tends to get bigger as you get older."},
    {icon: 2, title: "What is prostate cancer?", description: "Cancer is a group of diseases involving abnormal cell growth with the potential to invade or spread to other parts of the body. Prostate cancer is the most common cancer in men in the UK. It usually develops slowly, so there may be no signs for many years. About 1 in 9 men will be diagnosed with prostate cancer in their lifetime."},
    {icon: 2, title: "What are the symptoms of prostate cancer?", description: "Prostate cancer does not usually cause any symptoms until the cancer has grown large enough to put pressure on the tube that carries urine from the bladder out of the penis (urethra). Symptoms of prostate cancer can include: needing to pee more frequently, difficulty starting to pee (hesitancy), weak flow, feeling that your bladder has not emptied fully, and blood in urine and/or semen. These symptoms do not always mean you have prostate cancer. Many men's prostates get larger as they get older because of a non-cancerous condition called prostate enlargement."},
    {icon: 2, title: "Who does it affect and why?", description: "The chances of developing prostate cancer increase as you get older. Most cases develop in men aged 50 or older. For reasons not yet understood, prostate cancer is more common in men of African-Caribbean or African descent, and less common in Asian men. Men whose father or brother were affected by prostate cancer are at slightly increased risk themselves. Recent research also suggests that obesity increases the risk of prostate cancer."}
]

export let TreatmentInfo = [
    {icon: 3, title: "What are the most common treatment options?", description: "Treatment for prostate cancer will depend on your individual circumstances. For many men with prostate cancer, no treatment will be necessary. However, some men may recieve brachytherapy, radiotherapy or a prostatectomy. You will discuss your treatment options with your doctor."},
    {icon: 3, title: "What affects my treatment options?", description: "Doctors will use the results of your prostate examination, biopsy and scans to identify the 'stage' of your prostate cancer (how far the cancer has spread). The stage of the cancer will determine which types of treatments will be necessary. If prostate cancer is diagnosed at an early stage, the chances of survival are generally good."},
    {icon: 3, title: "What is 'Active Surveillance'?", description: "Active surveillance aims to avoid unnecessary treatment of harmless cancers while still providing timely treatment for men who need it. Active surveillance involves having regular PSA tests, MRI scans and sometimes biopsies to ensure any signs of progression are found as early as possible. If these tests reveal the cancer is changing or progressing, you can then make a decision about further treatment."},
    {icon: 3, title: "What is 'Watchful Waiting'?", description: "Watchful waiting is often recommended for older men when it's unlikely the cancer will affect their natural lifespan. If the cancer is in its early stages and not causing symptoms, you may decide to delay treatment and wait to see if any symptoms of progressive cancer develop."},
    {icon: 3, title: "What is a Radical Prostatectomy?", description: "A radical prostatectomy is the surgical removal of your prostate gland. This treatment is an option for curing prostate cancer that has not spread beyond the prostate or has not spread very far. Like any operation, this surgery carries some risks. A recent trial showed possible long-term side effects of radical prostatectomy may include an inability to get an erection and urinary incontinence."},
    {icon: 3, title: "What is Radiotherapy?", description: "Radiotherapy involves using radiation to kill cancerous cells. This treatment is an option for curing prostate cancer that has not spread beyond the prostate or has not spread very far. Radiotherapy can also be used to slow the progression of prostate cancer that's spread and relieve symptoms."},
    {icon: 3, title: "What is Brachytherapy?", description: "Brachytherapy is a form of radiotherapy where the radiation dose is delivered inside the prostate gland. It's also known as internal or interstitial radiotherapy. The radiation can be delivered using a number of tiny radioactive seeds surgically implanted into the tumour. This is called low dose rate brachytherapy."},
    {icon: 3, title: "What is Hormone Therapy?", description: "Hormone therapy is often used in combination with radiotherapy. For example, you may receive hormone therapy before undergoing radiotherapy to increase the chance of successful treatment. It may also be recommended after radiotherapy to reduce the chances of cancerous cells returning. Hormone therapy alone does not cure prostate cancer. It can be used to slow the progression of advanced prostate cancer and relieve symptoms."},
    {icon: 3, title: "What is Trans-urethral resection of the prostate (TURP)?", description: "TURP is a procedure that can help relieve pressure from the tube that carries urine from your bladder out of your penis (urethra) to treat any problematic symptoms you may have with urination. It does not cure the cancer."},
    {icon: 3, title: "What is High-intensity focused ultrasound (HIFU)?", description: "HIFU is sometimes used to treat men with localised prostate cancer that has not spread beyond their prostate. An ultrasound probe inserted into the bottom (rectum) releases high-frequency sound waves through the wall of the rectum. These sound waves kill cancer cells in the prostate gland by heating them to a high temperature. The risk of side effects from HIFU is usually lower than other treatments. HIFU is still undergoing clinical trials. It is not widely available and its long-term effectiveness has not yet been conclusively proven."},
    {icon: 3, title: "What is Cryotherapy?", description: "Cryotherapy is a method of killing cancer cells by freezing them. It's sometimes used to treat men with localised prostate cancer that has not spread beyond their prostate gland. Tiny probes called cryoneedles are inserted into the prostate gland through the wall of the rectum. They freeze the prostate gland and kill the cancer cells, but some normal cells also die. The aim is to kill cancer cells while causing as little damage as possible to healthy cells. Cryotherapy is still undergoing clinical trials for prostate cancer. It is not widely available and its long-term effectiveness has not yet been conclusively proven."},
    {icon: 3, title: "How is advanced prostate cancer treated?", description: "If the cancer has reached an advanced stage, it's no longer possible to cure it. But it may be possible to slow its progression, prolong your life and relieve symptoms. Treatment options include: radiotherapy, hormone treatment, chemotherapy"},
    
]

export let ManagementInfo = [
    {icon: 3, title: "What are common side effects?", description: "text goes here"},
    {icon: 3, title: "Sexual problems", description: "text goes here"},
    {icon: 3, title: "Bone health", description: "text goes here"},
    {icon: 3, title: "Managing with fatigue", description: "text goes here"}
]